extends: airbnb-base
rules:
  no-console: 0
  comma-dangle:
  - error
  - arrays: only-multiline
    objects: only-multiline
    imports: only-multiline
    exports: only-multiline
    functions: ignore
  function-paren-newline: 0
